export { default as About } from './About'
export { default as Skills } from './Skills'
export { default as Awards } from './Awards'
export { default as Certifications } from './Certifications'
export { default as Projects } from './Projects'